#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

// Scene
#define SCENE_POSITION_ATTRIB_LOCATION 0
#define SCENE_TEXCOORD_ATTRIB_LOCATION 1
#define SCENE_NORMAL_ATTRIB_LOCATION 2

#define SCENE_WATER_MAP_TEXTURE_BINDING 0
#define SCENE_SAND_MAP_TEXTURE_BINDING 1
#define SCENE_GRASS_MAP_TEXTURE_BINDING 2
#define SCENE_ROCK_MAP_TEXTURE_BINDING 3
#define SCENE_SNOW_MAP_TEXTURE_BINDING 4
#define SCENE_SKYBOX_MAP_TEXTURE_BINDING 5

#endif // PREAMBLE_GLSL